<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/metrics/v1/metrics.proto

namespace Opencensus\Proto\Metrics\V1;

if (false) {
    /**
     * This class is deprecated. Use Opencensus\Proto\Metrics\V1\DistributionValue\BucketOptions instead.
     * @deprecated
     */
    class DistributionValue_BucketOptions {}
}
class_exists(DistributionValue\BucketOptions::class);
@trigger_error('Opencensus\Proto\Metrics\V1\DistributionValue_BucketOptions is deprecated and will be removed in the next major release. Use Opencensus\Proto\Metrics\V1\DistributionValue\BucketOptions instead', E_USER_DEPRECATED);

