<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/metrics/v1/metrics.proto

namespace Opencensus\Proto\Metrics\V1;

if (false) {
    /**
     * This class is deprecated. Use Opencensus\Proto\Metrics\V1\DistributionValue\Exemplar instead.
     * @deprecated
     */
    class DistributionValue_Exemplar {}
}
class_exists(DistributionValue\Exemplar::class);
@trigger_error('Opencensus\Proto\Metrics\V1\DistributionValue_Exemplar is deprecated and will be removed in the next major release. Use Opencensus\Proto\Metrics\V1\DistributionValue\Exemplar instead', E_USER_DEPRECATED);

