<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/metrics/v1/metrics.proto

namespace Opencensus\Proto\Metrics\V1;

if (false) {
    /**
     * This class is deprecated. Use Opencensus\Proto\Metrics\V1\DistributionValue\Bucket instead.
     * @deprecated
     */
    class DistributionValue_Bucket {}
}
class_exists(DistributionValue\Bucket::class);
@trigger_error('Opencensus\Proto\Metrics\V1\DistributionValue_Bucket is deprecated and will be removed in the next major release. Use Opencensus\Proto\Metrics\V1\DistributionValue\Bucket instead', E_USER_DEPRECATED);

