<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/metrics/v1/metrics.proto

namespace Opencensus\Proto\Metrics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opencensus.proto.metrics.v1.LabelValue</code>
 */
class LabelValue extends \Google\Protobuf\Internal\Message
{
    /**
     * The value for the label.
     *
     * Generated from protobuf field <code>string value = 1;</code>
     */
    private $value = '';
    /**
     * If false the value field is ignored and considered not set.
     * This is used to differentiate a missing label from an empty string.
     *
     * Generated from protobuf field <code>bool has_value = 2;</code>
     */
    private $has_value = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $value
     *           The value for the label.
     *     @type bool $has_value
     *           If false the value field is ignored and considered not set.
     *           This is used to differentiate a missing label from an empty string.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Metrics\V1\Metrics::initOnce();
        parent::__construct($data);
    }

    /**
     * The value for the label.
     *
     * Generated from protobuf field <code>string value = 1;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * The value for the label.
     *
     * Generated from protobuf field <code>string value = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * If false the value field is ignored and considered not set.
     * This is used to differentiate a missing label from an empty string.
     *
     * Generated from protobuf field <code>bool has_value = 2;</code>
     * @return bool
     */
    public function getHasValue()
    {
        return $this->has_value;
    }

    /**
     * If false the value field is ignored and considered not set.
     * This is used to differentiate a missing label from an empty string.
     *
     * Generated from protobuf field <code>bool has_value = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setHasValue($var)
    {
        GPBUtil::checkBool($var);
        $this->has_value = $var;

        return $this;
    }

}

