<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/metrics/v1/metrics.proto

namespace Opencensus\Proto\Metrics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Defines a Metric which has one or more timeseries.
 *
 * Generated from protobuf message <code>opencensus.proto.metrics.v1.Metric</code>
 */
class Metric extends \Google\Protobuf\Internal\Message
{
    /**
     * The descriptor of the Metric.
     * TODO(issue #152): consider only sending the name of descriptor for
     * optimization.
     *
     * Generated from protobuf field <code>.opencensus.proto.metrics.v1.MetricDescriptor metric_descriptor = 1;</code>
     */
    private $metric_descriptor = null;
    /**
     * One or more timeseries for a single metric, where each timeseries has
     * one or more points.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.metrics.v1.TimeSeries timeseries = 2;</code>
     */
    private $timeseries;
    /**
     * The resource for the metric. If unset, it may be set to a default value
     * provided for a sequence of messages in an RPC stream.
     *
     * Generated from protobuf field <code>.opencensus.proto.resource.v1.Resource resource = 3;</code>
     */
    private $resource = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Opencensus\Proto\Metrics\V1\MetricDescriptor $metric_descriptor
     *           The descriptor of the Metric.
     *           TODO(issue #152): consider only sending the name of descriptor for
     *           optimization.
     *     @type \Opencensus\Proto\Metrics\V1\TimeSeries[]|\Google\Protobuf\Internal\RepeatedField $timeseries
     *           One or more timeseries for a single metric, where each timeseries has
     *           one or more points.
     *     @type \Opencensus\Proto\Resource\V1\Resource $resource
     *           The resource for the metric. If unset, it may be set to a default value
     *           provided for a sequence of messages in an RPC stream.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Metrics\V1\Metrics::initOnce();
        parent::__construct($data);
    }

    /**
     * The descriptor of the Metric.
     * TODO(issue #152): consider only sending the name of descriptor for
     * optimization.
     *
     * Generated from protobuf field <code>.opencensus.proto.metrics.v1.MetricDescriptor metric_descriptor = 1;</code>
     * @return \Opencensus\Proto\Metrics\V1\MetricDescriptor
     */
    public function getMetricDescriptor()
    {
        return $this->metric_descriptor;
    }

    /**
     * The descriptor of the Metric.
     * TODO(issue #152): consider only sending the name of descriptor for
     * optimization.
     *
     * Generated from protobuf field <code>.opencensus.proto.metrics.v1.MetricDescriptor metric_descriptor = 1;</code>
     * @param \Opencensus\Proto\Metrics\V1\MetricDescriptor $var
     * @return $this
     */
    public function setMetricDescriptor($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Metrics\V1\MetricDescriptor::class);
        $this->metric_descriptor = $var;

        return $this;
    }

    /**
     * One or more timeseries for a single metric, where each timeseries has
     * one or more points.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.metrics.v1.TimeSeries timeseries = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTimeseries()
    {
        return $this->timeseries;
    }

    /**
     * One or more timeseries for a single metric, where each timeseries has
     * one or more points.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.metrics.v1.TimeSeries timeseries = 2;</code>
     * @param \Opencensus\Proto\Metrics\V1\TimeSeries[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTimeseries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opencensus\Proto\Metrics\V1\TimeSeries::class);
        $this->timeseries = $arr;

        return $this;
    }

    /**
     * The resource for the metric. If unset, it may be set to a default value
     * provided for a sequence of messages in an RPC stream.
     *
     * Generated from protobuf field <code>.opencensus.proto.resource.v1.Resource resource = 3;</code>
     * @return \Opencensus\Proto\Resource\V1\Resource
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * The resource for the metric. If unset, it may be set to a default value
     * provided for a sequence of messages in an RPC stream.
     *
     * Generated from protobuf field <code>.opencensus.proto.resource.v1.Resource resource = 3;</code>
     * @param \Opencensus\Proto\Resource\V1\Resource $var
     * @return $this
     */
    public function setResource($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Resource\V1\Resource::class);
        $this->resource = $var;

        return $this;
    }

}

