<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/metrics/v1/metrics.proto

namespace Opencensus\Proto\Metrics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Defines a metric type and its schema.
 *
 * Generated from protobuf message <code>opencensus.proto.metrics.v1.MetricDescriptor</code>
 */
class MetricDescriptor extends \Google\Protobuf\Internal\Message
{
    /**
     * The metric type, including its DNS name prefix. It must be unique.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * A detailed description of the metric, which can be used in documentation.
     *
     * Generated from protobuf field <code>string description = 2;</code>
     */
    private $description = '';
    /**
     * The unit in which the metric value is reported. Follows the format
     * described by http://unitsofmeasure.org/ucum.html.
     *
     * Generated from protobuf field <code>string unit = 3;</code>
     */
    private $unit = '';
    /**
     * Generated from protobuf field <code>.opencensus.proto.metrics.v1.MetricDescriptor.Type type = 4;</code>
     */
    private $type = 0;
    /**
     * The label keys associated with the metric descriptor.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.metrics.v1.LabelKey label_keys = 5;</code>
     */
    private $label_keys;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The metric type, including its DNS name prefix. It must be unique.
     *     @type string $description
     *           A detailed description of the metric, which can be used in documentation.
     *     @type string $unit
     *           The unit in which the metric value is reported. Follows the format
     *           described by http://unitsofmeasure.org/ucum.html.
     *     @type int $type
     *     @type \Opencensus\Proto\Metrics\V1\LabelKey[]|\Google\Protobuf\Internal\RepeatedField $label_keys
     *           The label keys associated with the metric descriptor.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Metrics\V1\Metrics::initOnce();
        parent::__construct($data);
    }

    /**
     * The metric type, including its DNS name prefix. It must be unique.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The metric type, including its DNS name prefix. It must be unique.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * A detailed description of the metric, which can be used in documentation.
     *
     * Generated from protobuf field <code>string description = 2;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * A detailed description of the metric, which can be used in documentation.
     *
     * Generated from protobuf field <code>string description = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * The unit in which the metric value is reported. Follows the format
     * described by http://unitsofmeasure.org/ucum.html.
     *
     * Generated from protobuf field <code>string unit = 3;</code>
     * @return string
     */
    public function getUnit()
    {
        return $this->unit;
    }

    /**
     * The unit in which the metric value is reported. Follows the format
     * described by http://unitsofmeasure.org/ucum.html.
     *
     * Generated from protobuf field <code>string unit = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUnit($var)
    {
        GPBUtil::checkString($var, True);
        $this->unit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.opencensus.proto.metrics.v1.MetricDescriptor.Type type = 4;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.opencensus.proto.metrics.v1.MetricDescriptor.Type type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Opencensus\Proto\Metrics\V1\MetricDescriptor_Type::class);
        $this->type = $var;

        return $this;
    }

    /**
     * The label keys associated with the metric descriptor.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.metrics.v1.LabelKey label_keys = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLabelKeys()
    {
        return $this->label_keys;
    }

    /**
     * The label keys associated with the metric descriptor.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.metrics.v1.LabelKey label_keys = 5;</code>
     * @param \Opencensus\Proto\Metrics\V1\LabelKey[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLabelKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opencensus\Proto\Metrics\V1\LabelKey::class);
        $this->label_keys = $arr;

        return $this;
    }

}

