<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/metrics/v1/metrics.proto

namespace Opencensus\Proto\Metrics\V1;

if (false) {
    /**
     * This class is deprecated. Use Opencensus\Proto\Metrics\V1\MetricDescriptor\Type instead.
     * @deprecated
     */
    class MetricDescriptor_Type {}
}
class_exists(MetricDescriptor\Type::class);
@trigger_error('Opencensus\Proto\Metrics\V1\MetricDescriptor_Type is deprecated and will be removed in the next major release. Use Opencensus\Proto\Metrics\V1\MetricDescriptor\Type instead', E_USER_DEPRECATED);

