<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/metrics/v1/metrics.proto

namespace Opencensus\Proto\Metrics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A timestamped measurement.
 *
 * Generated from protobuf message <code>opencensus.proto.metrics.v1.Point</code>
 */
class Point extends \Google\Protobuf\Internal\Message
{
    /**
     * The moment when this point was recorded. Inclusive.
     * If not specified, the timestamp will be decided by the backend.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    private $timestamp = null;
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $timestamp
     *           The moment when this point was recorded. Inclusive.
     *           If not specified, the timestamp will be decided by the backend.
     *     @type int|string $int64_value
     *           A 64-bit integer.
     *     @type float $double_value
     *           A 64-bit double-precision floating-point number.
     *     @type \Opencensus\Proto\Metrics\V1\DistributionValue $distribution_value
     *           A distribution value.
     *     @type \Opencensus\Proto\Metrics\V1\SummaryValue $summary_value
     *           A summary value. This is not recommended, since it cannot be aggregated.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Metrics\V1\Metrics::initOnce();
        parent::__construct($data);
    }

    /**
     * The moment when this point was recorded. Inclusive.
     * If not specified, the timestamp will be decided by the backend.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 1;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * The moment when this point was recorded. Inclusive.
     * If not specified, the timestamp will be decided by the backend.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * A 64-bit integer.
     *
     * Generated from protobuf field <code>int64 int64_value = 2;</code>
     * @return int|string
     */
    public function getInt64Value()
    {
        return $this->readOneof(2);
    }

    /**
     * A 64-bit integer.
     *
     * Generated from protobuf field <code>int64 int64_value = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInt64Value($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * A 64-bit double-precision floating-point number.
     *
     * Generated from protobuf field <code>double double_value = 3;</code>
     * @return float
     */
    public function getDoubleValue()
    {
        return $this->readOneof(3);
    }

    /**
     * A 64-bit double-precision floating-point number.
     *
     * Generated from protobuf field <code>double double_value = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * A distribution value.
     *
     * Generated from protobuf field <code>.opencensus.proto.metrics.v1.DistributionValue distribution_value = 4;</code>
     * @return \Opencensus\Proto\Metrics\V1\DistributionValue
     */
    public function getDistributionValue()
    {
        return $this->readOneof(4);
    }

    /**
     * A distribution value.
     *
     * Generated from protobuf field <code>.opencensus.proto.metrics.v1.DistributionValue distribution_value = 4;</code>
     * @param \Opencensus\Proto\Metrics\V1\DistributionValue $var
     * @return $this
     */
    public function setDistributionValue($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Metrics\V1\DistributionValue::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * A summary value. This is not recommended, since it cannot be aggregated.
     *
     * Generated from protobuf field <code>.opencensus.proto.metrics.v1.SummaryValue summary_value = 5;</code>
     * @return \Opencensus\Proto\Metrics\V1\SummaryValue
     */
    public function getSummaryValue()
    {
        return $this->readOneof(5);
    }

    /**
     * A summary value. This is not recommended, since it cannot be aggregated.
     *
     * Generated from protobuf field <code>.opencensus.proto.metrics.v1.SummaryValue summary_value = 5;</code>
     * @param \Opencensus\Proto\Metrics\V1\SummaryValue $var
     * @return $this
     */
    public function setSummaryValue($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Metrics\V1\SummaryValue::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

