<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/metrics/v1/metrics.proto

namespace Opencensus\Proto\Metrics\V1;

if (false) {
    /**
     * This class is deprecated. Use Opencensus\Proto\Metrics\V1\SummaryValue\Snapshot\ValueAtPercentile instead.
     * @deprecated
     */
    class SummaryValue_Snapshot_ValueAtPercentile {}
}
class_exists(SummaryValue\Snapshot\ValueAtPercentile::class);
@trigger_error('Opencensus\Proto\Metrics\V1\SummaryValue_Snapshot_ValueAtPercentile is deprecated and will be removed in the next major release. Use Opencensus\Proto\Metrics\V1\SummaryValue\Snapshot\ValueAtPercentile instead', E_USER_DEPRECATED);

