<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/metrics/v1/metrics.proto

namespace Opencensus\Proto\Metrics\V1;

if (false) {
    /**
     * This class is deprecated. Use Opencensus\Proto\Metrics\V1\SummaryValue\Snapshot instead.
     * @deprecated
     */
    class SummaryValue_Snapshot {}
}
class_exists(SummaryValue\Snapshot::class);
@trigger_error('Opencensus\Proto\Metrics\V1\SummaryValue_Snapshot is deprecated and will be removed in the next major release. Use Opencensus\Proto\Metrics\V1\SummaryValue\Snapshot instead', E_USER_DEPRECATED);

