<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/metrics/v1/metrics.proto

namespace Opencensus\Proto\Metrics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A collection of data points that describes the time-varying values
 * of a metric.
 *
 * Generated from protobuf message <code>opencensus.proto.metrics.v1.TimeSeries</code>
 */
class TimeSeries extends \Google\Protobuf\Internal\Message
{
    /**
     * Must be present for cumulative metrics. The time when the cumulative value
     * was reset to zero. Exclusive. The cumulative value is over the time interval
     * (start_timestamp, timestamp]. If not specified, the backend can use the
     * previous recorded value.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_timestamp = 1;</code>
     */
    private $start_timestamp = null;
    /**
     * The set of label values that uniquely identify this timeseries. Applies to
     * all points. The order of label values must match that of label keys in the
     * metric descriptor.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.metrics.v1.LabelValue label_values = 2;</code>
     */
    private $label_values;
    /**
     * The data points of this timeseries. Point.value type MUST match the
     * MetricDescriptor.type.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.metrics.v1.Point points = 3;</code>
     */
    private $points;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $start_timestamp
     *           Must be present for cumulative metrics. The time when the cumulative value
     *           was reset to zero. Exclusive. The cumulative value is over the time interval
     *           (start_timestamp, timestamp]. If not specified, the backend can use the
     *           previous recorded value.
     *     @type \Opencensus\Proto\Metrics\V1\LabelValue[]|\Google\Protobuf\Internal\RepeatedField $label_values
     *           The set of label values that uniquely identify this timeseries. Applies to
     *           all points. The order of label values must match that of label keys in the
     *           metric descriptor.
     *     @type \Opencensus\Proto\Metrics\V1\Point[]|\Google\Protobuf\Internal\RepeatedField $points
     *           The data points of this timeseries. Point.value type MUST match the
     *           MetricDescriptor.type.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Metrics\V1\Metrics::initOnce();
        parent::__construct($data);
    }

    /**
     * Must be present for cumulative metrics. The time when the cumulative value
     * was reset to zero. Exclusive. The cumulative value is over the time interval
     * (start_timestamp, timestamp]. If not specified, the backend can use the
     * previous recorded value.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_timestamp = 1;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getStartTimestamp()
    {
        return $this->start_timestamp;
    }

    /**
     * Must be present for cumulative metrics. The time when the cumulative value
     * was reset to zero. Exclusive. The cumulative value is over the time interval
     * (start_timestamp, timestamp]. If not specified, the backend can use the
     * previous recorded value.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_timestamp = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->start_timestamp = $var;

        return $this;
    }

    /**
     * The set of label values that uniquely identify this timeseries. Applies to
     * all points. The order of label values must match that of label keys in the
     * metric descriptor.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.metrics.v1.LabelValue label_values = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLabelValues()
    {
        return $this->label_values;
    }

    /**
     * The set of label values that uniquely identify this timeseries. Applies to
     * all points. The order of label values must match that of label keys in the
     * metric descriptor.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.metrics.v1.LabelValue label_values = 2;</code>
     * @param \Opencensus\Proto\Metrics\V1\LabelValue[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLabelValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opencensus\Proto\Metrics\V1\LabelValue::class);
        $this->label_values = $arr;

        return $this;
    }

    /**
     * The data points of this timeseries. Point.value type MUST match the
     * MetricDescriptor.type.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.metrics.v1.Point points = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPoints()
    {
        return $this->points;
    }

    /**
     * The data points of this timeseries. Point.value type MUST match the
     * MetricDescriptor.type.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.metrics.v1.Point points = 3;</code>
     * @param \Opencensus\Proto\Metrics\V1\Point[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPoints($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opencensus\Proto\Metrics\V1\Point::class);
        $this->points = $arr;

        return $this;
    }

}

