<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/stats/v1/stats.proto

namespace Opencensus\Proto\Stats\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opencensus.proto.stats.v1.DistributionAggregation</code>
 */
class DistributionAggregation extends \Google\Protobuf\Internal\Message
{
    /**
     * A Distribution may optionally contain a histogram of the values in the
     * population. The bucket boundaries for that histogram are described by
     * `bucket_bounds`. This defines `size(bucket_bounds) + 1` (= N)
     * buckets. The boundaries for bucket index i are:
     * (-infinity, bucket_bounds[i]) for i == 0
     * [bucket_bounds[i-1], bucket_bounds[i]) for 0 < i < N-2
     * [bucket_bounds[i-1], +infinity) for i == N-1
     * i.e. an underflow bucket (number 0), zero or more finite buckets (1
     * through N - 2, and an overflow bucket (N - 1), with inclusive lower
     * bounds and exclusive upper bounds.
     * If `bucket_bounds` has no elements (zero size), then there is no
     * histogram associated with the Distribution. If `bucket_bounds` has only
     * one element, there are no finite buckets, and that single element is the
     * common boundary of the overflow and underflow buckets. The values must
     * be monotonically increasing.
     *
     * Generated from protobuf field <code>repeated double bucket_bounds = 1;</code>
     */
    private $bucket_bounds;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float[]|\Google\Protobuf\Internal\RepeatedField $bucket_bounds
     *           A Distribution may optionally contain a histogram of the values in the
     *           population. The bucket boundaries for that histogram are described by
     *           `bucket_bounds`. This defines `size(bucket_bounds) + 1` (= N)
     *           buckets. The boundaries for bucket index i are:
     *           (-infinity, bucket_bounds[i]) for i == 0
     *           [bucket_bounds[i-1], bucket_bounds[i]) for 0 < i < N-2
     *           [bucket_bounds[i-1], +infinity) for i == N-1
     *           i.e. an underflow bucket (number 0), zero or more finite buckets (1
     *           through N - 2, and an overflow bucket (N - 1), with inclusive lower
     *           bounds and exclusive upper bounds.
     *           If `bucket_bounds` has no elements (zero size), then there is no
     *           histogram associated with the Distribution. If `bucket_bounds` has only
     *           one element, there are no finite buckets, and that single element is the
     *           common boundary of the overflow and underflow buckets. The values must
     *           be monotonically increasing.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Stats\V1\Stats::initOnce();
        parent::__construct($data);
    }

    /**
     * A Distribution may optionally contain a histogram of the values in the
     * population. The bucket boundaries for that histogram are described by
     * `bucket_bounds`. This defines `size(bucket_bounds) + 1` (= N)
     * buckets. The boundaries for bucket index i are:
     * (-infinity, bucket_bounds[i]) for i == 0
     * [bucket_bounds[i-1], bucket_bounds[i]) for 0 < i < N-2
     * [bucket_bounds[i-1], +infinity) for i == N-1
     * i.e. an underflow bucket (number 0), zero or more finite buckets (1
     * through N - 2, and an overflow bucket (N - 1), with inclusive lower
     * bounds and exclusive upper bounds.
     * If `bucket_bounds` has no elements (zero size), then there is no
     * histogram associated with the Distribution. If `bucket_bounds` has only
     * one element, there are no finite buckets, and that single element is the
     * common boundary of the overflow and underflow buckets. The values must
     * be monotonically increasing.
     *
     * Generated from protobuf field <code>repeated double bucket_bounds = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBucketBounds()
    {
        return $this->bucket_bounds;
    }

    /**
     * A Distribution may optionally contain a histogram of the values in the
     * population. The bucket boundaries for that histogram are described by
     * `bucket_bounds`. This defines `size(bucket_bounds) + 1` (= N)
     * buckets. The boundaries for bucket index i are:
     * (-infinity, bucket_bounds[i]) for i == 0
     * [bucket_bounds[i-1], bucket_bounds[i]) for 0 < i < N-2
     * [bucket_bounds[i-1], +infinity) for i == N-1
     * i.e. an underflow bucket (number 0), zero or more finite buckets (1
     * through N - 2, and an overflow bucket (N - 1), with inclusive lower
     * bounds and exclusive upper bounds.
     * If `bucket_bounds` has no elements (zero size), then there is no
     * histogram associated with the Distribution. If `bucket_bounds` has only
     * one element, there are no finite buckets, and that single element is the
     * common boundary of the overflow and underflow buckets. The values must
     * be monotonically increasing.
     *
     * Generated from protobuf field <code>repeated double bucket_bounds = 1;</code>
     * @param float[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBucketBounds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->bucket_bounds = $arr;

        return $this;
    }

}

