<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/stats/v1/stats.proto

namespace Opencensus\Proto\Stats\V1;

if (false) {
    /**
     * This class is deprecated. Use Opencensus\Proto\Stats\V1\Measure\Type instead.
     * @deprecated
     */
    class Measure_Type {}
}
class_exists(Measure\Type::class);
@trigger_error('Opencensus\Proto\Stats\V1\Measure_Type is deprecated and will be removed in the next major release. Use Opencensus\Proto\Stats\V1\Measure\Type instead', E_USER_DEPRECATED);

