<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/trace/v1/trace_config.proto

namespace Opencensus\Proto\Trace\V1;

if (false) {
    /**
     * This class is deprecated. Use Opencensus\Proto\Trace\V1\ConstantSampler\ConstantDecision instead.
     * @deprecated
     */
    class ConstantSampler_ConstantDecision {}
}
class_exists(ConstantSampler\ConstantDecision::class);
@trigger_error('Opencensus\Proto\Trace\V1\ConstantSampler_ConstantDecision is deprecated and will be removed in the next major release. Use Opencensus\Proto\Trace\V1\ConstantSampler\ConstantDecision instead', E_USER_DEPRECATED);

