<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/trace/v1/trace_config.proto

namespace Opencensus\Proto\Trace\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Sampler that tries to uniformly sample traces with a given probability.
 * The probability of sampling a trace is equal to that of the specified probability.
 *
 * Generated from protobuf message <code>opencensus.proto.trace.v1.ProbabilitySampler</code>
 */
class ProbabilitySampler extends \Google\Protobuf\Internal\Message
{
    /**
     * The desired probability of sampling. Must be within [0.0, 1.0].
     *
     * Generated from protobuf field <code>double samplingProbability = 1;</code>
     */
    private $samplingProbability = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $samplingProbability
     *           The desired probability of sampling. Must be within [0.0, 1.0].
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Trace\V1\TraceConfig::initOnce();
        parent::__construct($data);
    }

    /**
     * The desired probability of sampling. Must be within [0.0, 1.0].
     *
     * Generated from protobuf field <code>double samplingProbability = 1;</code>
     * @return float
     */
    public function getSamplingProbability()
    {
        return $this->samplingProbability;
    }

    /**
     * The desired probability of sampling. Must be within [0.0, 1.0].
     *
     * Generated from protobuf field <code>double samplingProbability = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setSamplingProbability($var)
    {
        GPBUtil::checkDouble($var);
        $this->samplingProbability = $var;

        return $this;
    }

}

