<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/trace/v1/trace.proto

namespace Opencensus\Proto\Trace\V1;

if (false) {
    /**
     * This class is deprecated. Use Opencensus\Proto\Trace\V1\Span\Attributes instead.
     * @deprecated
     */
    class Span_Attributes {}
}
class_exists(Span\Attributes::class);
@trigger_error('Opencensus\Proto\Trace\V1\Span_Attributes is deprecated and will be removed in the next major release. Use Opencensus\Proto\Trace\V1\Span\Attributes instead', E_USER_DEPRECATED);

