<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/trace/v1/trace.proto

namespace Opencensus\Proto\Trace\V1;

if (false) {
    /**
     * This class is deprecated. Use Opencensus\Proto\Trace\V1\Span\Links instead.
     * @deprecated
     */
    class Span_Links {}
}
class_exists(Span\Links::class);
@trigger_error('Opencensus\Proto\Trace\V1\Span_Links is deprecated and will be removed in the next major release. Use Opencensus\Proto\Trace\V1\Span\Links instead', E_USER_DEPRECATED);

