<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/trace/v1/trace.proto

namespace Opencensus\Proto\Trace\V1;

if (false) {
    /**
     * This class is deprecated. Use Opencensus\Proto\Trace\V1\Span\Link\Type instead.
     * @deprecated
     */
    class Span_Link_Type {}
}
class_exists(Span\Link\Type::class);
@trigger_error('Opencensus\Proto\Trace\V1\Span_Link_Type is deprecated and will be removed in the next major release. Use Opencensus\Proto\Trace\V1\Span\Link\Type instead', E_USER_DEPRECATED);

