<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/trace/v1/trace.proto

namespace Opencensus\Proto\Trace\V1;

if (false) {
    /**
     * This class is deprecated. Use Opencensus\Proto\Trace\V1\Span\TimeEvent\Annotation instead.
     * @deprecated
     */
    class Span_TimeEvent_Annotation {}
}
class_exists(Span\TimeEvent\Annotation::class);
@trigger_error('Opencensus\Proto\Trace\V1\Span_TimeEvent_Annotation is deprecated and will be removed in the next major release. Use Opencensus\Proto\Trace\V1\Span\TimeEvent\Annotation instead', E_USER_DEPRECATED);

