<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/trace/v1/trace.proto

namespace Opencensus\Proto\Trace\V1;

if (false) {
    /**
     * This class is deprecated. Use Opencensus\Proto\Trace\V1\StackTrace\StackFrames instead.
     * @deprecated
     */
    class StackTrace_StackFrames {}
}
class_exists(StackTrace\StackFrames::class);
@trigger_error('Opencensus\Proto\Trace\V1\StackTrace_StackFrames is deprecated and will be removed in the next major release. Use Opencensus\Proto\Trace\V1\StackTrace\StackFrames instead', E_USER_DEPRECATED);

