<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/agent/trace/v1/trace_service.proto

namespace Opencensus\Proto\Agent\Trace\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opencensus.proto.agent.trace.v1.CurrentLibraryConfig</code>
 */
class CurrentLibraryConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * This is required only in the first message on the stream or if the
     * previous sent CurrentLibraryConfig message has a different Node (e.g.
     * when the same RPC is used to configure multiple Applications).
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.Node node = 1;</code>
     */
    private $node = null;
    /**
     * Current configuration.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TraceConfig config = 2;</code>
     */
    private $config = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Opencensus\Proto\Agent\Common\V1\Node $node
     *           This is required only in the first message on the stream or if the
     *           previous sent CurrentLibraryConfig message has a different Node (e.g.
     *           when the same RPC is used to configure multiple Applications).
     *     @type \Opencensus\Proto\Trace\V1\TraceConfig $config
     *           Current configuration.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Agent\Trace\V1\TraceService::initOnce();
        parent::__construct($data);
    }

    /**
     * This is required only in the first message on the stream or if the
     * previous sent CurrentLibraryConfig message has a different Node (e.g.
     * when the same RPC is used to configure multiple Applications).
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.Node node = 1;</code>
     * @return \Opencensus\Proto\Agent\Common\V1\Node
     */
    public function getNode()
    {
        return $this->node;
    }

    /**
     * This is required only in the first message on the stream or if the
     * previous sent CurrentLibraryConfig message has a different Node (e.g.
     * when the same RPC is used to configure multiple Applications).
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.Node node = 1;</code>
     * @param \Opencensus\Proto\Agent\Common\V1\Node $var
     * @return $this
     */
    public function setNode($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Agent\Common\V1\Node::class);
        $this->node = $var;

        return $this;
    }

    /**
     * Current configuration.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TraceConfig config = 2;</code>
     * @return \Opencensus\Proto\Trace\V1\TraceConfig
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Current configuration.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TraceConfig config = 2;</code>
     * @param \Opencensus\Proto\Trace\V1\TraceConfig $var
     * @return $this
     */
    public function setConfig($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Trace\V1\TraceConfig::class);
        $this->config = $var;

        return $this;
    }

}

