<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/agent/trace/v1/trace_service.proto

namespace Opencensus\Proto\Agent\Trace\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opencensus.proto.agent.trace.v1.ExportTraceServiceResponse</code>
 */
class ExportTraceServiceResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Agent\Trace\V1\TraceService::initOnce();
        parent::__construct($data);
    }

}

