<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/metrics/v1/metrics.proto

namespace Opencensus\Proto\Metrics\V1\DistributionValue;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A Distribution may optionally contain a histogram of the values in the
 * population. The bucket boundaries for that histogram are described by
 * BucketOptions.
 * If bucket_options has no type, then there is no histogram associated with
 * the Distribution.
 *
 * Generated from protobuf message <code>opencensus.proto.metrics.v1.DistributionValue.BucketOptions</code>
 */
class BucketOptions extends \Google\Protobuf\Internal\Message
{
    protected $type;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Opencensus\Proto\Metrics\V1\DistributionValue\BucketOptions\Explicit $explicit
     *           Bucket with explicit bounds.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Metrics\V1\Metrics::initOnce();
        parent::__construct($data);
    }

    /**
     * Bucket with explicit bounds.
     *
     * Generated from protobuf field <code>.opencensus.proto.metrics.v1.DistributionValue.BucketOptions.Explicit explicit = 1;</code>
     * @return \Opencensus\Proto\Metrics\V1\DistributionValue\BucketOptions\Explicit
     */
    public function getExplicit()
    {
        return $this->readOneof(1);
    }

    /**
     * Bucket with explicit bounds.
     *
     * Generated from protobuf field <code>.opencensus.proto.metrics.v1.DistributionValue.BucketOptions.Explicit explicit = 1;</code>
     * @param \Opencensus\Proto\Metrics\V1\DistributionValue\BucketOptions\Explicit $var
     * @return $this
     */
    public function setExplicit($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Metrics\V1\DistributionValue_BucketOptions_Explicit::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->whichOneof("type");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(BucketOptions::class, \Opencensus\Proto\Metrics\V1\DistributionValue_BucketOptions::class);

