<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/metrics/v1/metrics.proto

namespace Opencensus\Proto\Metrics\V1\DistributionValue;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Exemplars are example points that may be used to annotate aggregated
 * Distribution values. They are metadata that gives information about a
 * particular value added to a Distribution bucket.
 *
 * Generated from protobuf message <code>opencensus.proto.metrics.v1.DistributionValue.Exemplar</code>
 */
class Exemplar extends \Google\Protobuf\Internal\Message
{
    /**
     * Value of the exemplar point. It determines which bucket the exemplar
     * belongs to.
     *
     * Generated from protobuf field <code>double value = 1;</code>
     */
    private $value = 0.0;
    /**
     * The observation (sampling) time of the above value.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    private $timestamp = null;
    /**
     * Contextual information about the example value.
     *
     * Generated from protobuf field <code>map<string, string> attachments = 3;</code>
     */
    private $attachments;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $value
     *           Value of the exemplar point. It determines which bucket the exemplar
     *           belongs to.
     *     @type \Google\Protobuf\Timestamp $timestamp
     *           The observation (sampling) time of the above value.
     *     @type array|\Google\Protobuf\Internal\MapField $attachments
     *           Contextual information about the example value.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Metrics\V1\Metrics::initOnce();
        parent::__construct($data);
    }

    /**
     * Value of the exemplar point. It determines which bucket the exemplar
     * belongs to.
     *
     * Generated from protobuf field <code>double value = 1;</code>
     * @return float
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Value of the exemplar point. It determines which bucket the exemplar
     * belongs to.
     *
     * Generated from protobuf field <code>double value = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->value = $var;

        return $this;
    }

    /**
     * The observation (sampling) time of the above value.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * The observation (sampling) time of the above value.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Contextual information about the example value.
     *
     * Generated from protobuf field <code>map<string, string> attachments = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAttachments()
    {
        return $this->attachments;
    }

    /**
     * Contextual information about the example value.
     *
     * Generated from protobuf field <code>map<string, string> attachments = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAttachments($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->attachments = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Exemplar::class, \Opencensus\Proto\Metrics\V1\DistributionValue_Exemplar::class);

