<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/trace/v1/trace.proto

namespace Opencensus\Proto\Trace\V1\Span\TimeEvent;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A text annotation with a set of attributes.
 *
 * Generated from protobuf message <code>opencensus.proto.trace.v1.Span.TimeEvent.Annotation</code>
 */
class Annotation extends \Google\Protobuf\Internal\Message
{
    /**
     * A user-supplied message describing the event.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TruncatableString description = 1;</code>
     */
    private $description = null;
    /**
     * A set of attributes on the annotation.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.Span.Attributes attributes = 2;</code>
     */
    private $attributes = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Opencensus\Proto\Trace\V1\TruncatableString $description
     *           A user-supplied message describing the event.
     *     @type \Opencensus\Proto\Trace\V1\Span\Attributes $attributes
     *           A set of attributes on the annotation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Trace\V1\Trace::initOnce();
        parent::__construct($data);
    }

    /**
     * A user-supplied message describing the event.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TruncatableString description = 1;</code>
     * @return \Opencensus\Proto\Trace\V1\TruncatableString
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * A user-supplied message describing the event.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TruncatableString description = 1;</code>
     * @param \Opencensus\Proto\Trace\V1\TruncatableString $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Trace\V1\TruncatableString::class);
        $this->description = $var;

        return $this;
    }

    /**
     * A set of attributes on the annotation.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.Span.Attributes attributes = 2;</code>
     * @return \Opencensus\Proto\Trace\V1\Span\Attributes
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * A set of attributes on the annotation.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.Span.Attributes attributes = 2;</code>
     * @param \Opencensus\Proto\Trace\V1\Span\Attributes $var
     * @return $this
     */
    public function setAttributes($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Trace\V1\Span_Attributes::class);
        $this->attributes = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Annotation::class, \Opencensus\Proto\Trace\V1\Span_TimeEvent_Annotation::class);

