<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/metrics/v1/metrics.proto

namespace Opencensus\Proto\Metrics\V1\SummaryValue\Snapshot;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Represents the value at a given percentile of a distribution.
 *
 * Generated from protobuf message <code>opencensus.proto.metrics.v1.SummaryValue.Snapshot.ValueAtPercentile</code>
 */
class ValueAtPercentile extends \Google\Protobuf\Internal\Message
{
    /**
     * The percentile of a distribution. Must be in the interval
     * (0.0, 100.0].
     *
     * Generated from protobuf field <code>double percentile = 1;</code>
     */
    private $percentile = 0.0;
    /**
     * The value at the given percentile of a distribution.
     *
     * Generated from protobuf field <code>double value = 2;</code>
     */
    private $value = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $percentile
     *           The percentile of a distribution. Must be in the interval
     *           (0.0, 100.0].
     *     @type float $value
     *           The value at the given percentile of a distribution.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Metrics\V1\Metrics::initOnce();
        parent::__construct($data);
    }

    /**
     * The percentile of a distribution. Must be in the interval
     * (0.0, 100.0].
     *
     * Generated from protobuf field <code>double percentile = 1;</code>
     * @return float
     */
    public function getPercentile()
    {
        return $this->percentile;
    }

    /**
     * The percentile of a distribution. Must be in the interval
     * (0.0, 100.0].
     *
     * Generated from protobuf field <code>double percentile = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setPercentile($var)
    {
        GPBUtil::checkDouble($var);
        $this->percentile = $var;

        return $this;
    }

    /**
     * The value at the given percentile of a distribution.
     *
     * Generated from protobuf field <code>double value = 2;</code>
     * @return float
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * The value at the given percentile of a distribution.
     *
     * Generated from protobuf field <code>double value = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->value = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ValueAtPercentile::class, \Opencensus\Proto\Metrics\V1\SummaryValue_Snapshot_ValueAtPercentile::class);

