<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/agent/metrics/v1/metrics_service.proto

namespace Opencensus\Proto\Agent\Metrics\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opencensus.proto.agent.metrics.v1.ExportMetricsServiceRequest</code>
 */
class ExportMetricsServiceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * This is required only in the first message on the stream or if the
     * previous sent ExportMetricsServiceRequest message has a different Node (e.g.
     * when the same RPC is used to send Metrics from multiple Applications).
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.Node node = 1;</code>
     */
    private $node = null;
    /**
     * A list of metrics that belong to the last received Node.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.metrics.v1.Metric metrics = 2;</code>
     */
    private $metrics;
    /**
     * The resource for the metrics in this message that do not have an explicit
     * resource set.
     * If unset, the most recently set resource in the RPC stream applies. It is
     * valid to never be set within a stream, e.g. when no resource info is known
     * at all or when all sent metrics have an explicit resource set.
     *
     * Generated from protobuf field <code>.opencensus.proto.resource.v1.Resource resource = 3;</code>
     */
    private $resource = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Opencensus\Proto\Agent\Common\V1\Node $node
     *           This is required only in the first message on the stream or if the
     *           previous sent ExportMetricsServiceRequest message has a different Node (e.g.
     *           when the same RPC is used to send Metrics from multiple Applications).
     *     @type \Opencensus\Proto\Metrics\V1\Metric[]|\Google\Protobuf\Internal\RepeatedField $metrics
     *           A list of metrics that belong to the last received Node.
     *     @type \Opencensus\Proto\Resource\V1\Resource $resource
     *           The resource for the metrics in this message that do not have an explicit
     *           resource set.
     *           If unset, the most recently set resource in the RPC stream applies. It is
     *           valid to never be set within a stream, e.g. when no resource info is known
     *           at all or when all sent metrics have an explicit resource set.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Agent\Metrics\V1\MetricsService::initOnce();
        parent::__construct($data);
    }

    /**
     * This is required only in the first message on the stream or if the
     * previous sent ExportMetricsServiceRequest message has a different Node (e.g.
     * when the same RPC is used to send Metrics from multiple Applications).
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.Node node = 1;</code>
     * @return \Opencensus\Proto\Agent\Common\V1\Node
     */
    public function getNode()
    {
        return $this->node;
    }

    /**
     * This is required only in the first message on the stream or if the
     * previous sent ExportMetricsServiceRequest message has a different Node (e.g.
     * when the same RPC is used to send Metrics from multiple Applications).
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.Node node = 1;</code>
     * @param \Opencensus\Proto\Agent\Common\V1\Node $var
     * @return $this
     */
    public function setNode($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Agent\Common\V1\Node::class);
        $this->node = $var;

        return $this;
    }

    /**
     * A list of metrics that belong to the last received Node.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.metrics.v1.Metric metrics = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMetrics()
    {
        return $this->metrics;
    }

    /**
     * A list of metrics that belong to the last received Node.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.metrics.v1.Metric metrics = 2;</code>
     * @param \Opencensus\Proto\Metrics\V1\Metric[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMetrics($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opencensus\Proto\Metrics\V1\Metric::class);
        $this->metrics = $arr;

        return $this;
    }

    /**
     * The resource for the metrics in this message that do not have an explicit
     * resource set.
     * If unset, the most recently set resource in the RPC stream applies. It is
     * valid to never be set within a stream, e.g. when no resource info is known
     * at all or when all sent metrics have an explicit resource set.
     *
     * Generated from protobuf field <code>.opencensus.proto.resource.v1.Resource resource = 3;</code>
     * @return \Opencensus\Proto\Resource\V1\Resource
     */
    public function getResource()
    {
        return $this->resource;
    }

    /**
     * The resource for the metrics in this message that do not have an explicit
     * resource set.
     * If unset, the most recently set resource in the RPC stream applies. It is
     * valid to never be set within a stream, e.g. when no resource info is known
     * at all or when all sent metrics have an explicit resource set.
     *
     * Generated from protobuf field <code>.opencensus.proto.resource.v1.Resource resource = 3;</code>
     * @param \Opencensus\Proto\Resource\V1\Resource $var
     * @return $this
     */
    public function setResource($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Resource\V1\Resource::class);
        $this->resource = $var;

        return $this;
    }

}

