<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/agent/common/v1/common.proto

namespace Opencensus\Proto\Agent\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Information on OpenCensus Library.
 *
 * Generated from protobuf message <code>opencensus.proto.agent.common.v1.LibraryInfo</code>
 */
class LibraryInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Language of OpenCensus Library.
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.LibraryInfo.Language language = 1;</code>
     */
    private $language = 0;
    /**
     * Version of Agent exporter of Library.
     *
     * Generated from protobuf field <code>string exporter_version = 2;</code>
     */
    private $exporter_version = '';
    /**
     * Version of OpenCensus Library.
     *
     * Generated from protobuf field <code>string core_library_version = 3;</code>
     */
    private $core_library_version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $language
     *           Language of OpenCensus Library.
     *     @type string $exporter_version
     *           Version of Agent exporter of Library.
     *     @type string $core_library_version
     *           Version of OpenCensus Library.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Agent\Common\V1\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Language of OpenCensus Library.
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.LibraryInfo.Language language = 1;</code>
     * @return int
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * Language of OpenCensus Library.
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.LibraryInfo.Language language = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLanguage($var)
    {
        GPBUtil::checkEnum($var, \Opencensus\Proto\Agent\Common\V1\LibraryInfo_Language::class);
        $this->language = $var;

        return $this;
    }

    /**
     * Version of Agent exporter of Library.
     *
     * Generated from protobuf field <code>string exporter_version = 2;</code>
     * @return string
     */
    public function getExporterVersion()
    {
        return $this->exporter_version;
    }

    /**
     * Version of Agent exporter of Library.
     *
     * Generated from protobuf field <code>string exporter_version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setExporterVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->exporter_version = $var;

        return $this;
    }

    /**
     * Version of OpenCensus Library.
     *
     * Generated from protobuf field <code>string core_library_version = 3;</code>
     * @return string
     */
    public function getCoreLibraryVersion()
    {
        return $this->core_library_version;
    }

    /**
     * Version of OpenCensus Library.
     *
     * Generated from protobuf field <code>string core_library_version = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCoreLibraryVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->core_library_version = $var;

        return $this;
    }

}

