<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/agent/common/v1/common.proto

namespace Opencensus\Proto\Agent\Common\V1;

if (false) {
    /**
     * This class is deprecated. Use Opencensus\Proto\Agent\Common\V1\LibraryInfo\Language instead.
     * @deprecated
     */
    class LibraryInfo_Language {}
}
class_exists(LibraryInfo\Language::class);
@trigger_error('Opencensus\Proto\Agent\Common\V1\LibraryInfo_Language is deprecated and will be removed in the next major release. Use Opencensus\Proto\Agent\Common\V1\LibraryInfo\Language instead', E_USER_DEPRECATED);

