<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/agent/common/v1/common.proto

namespace Opencensus\Proto\Agent\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Identifier metadata of the Node that produces the span or tracing data.
 * Note, this is not the metadata about the Node or service that is described by associated spans.
 * In the future we plan to extend the identifier proto definition to support
 * additional information (e.g cloud id, etc.)
 *
 * Generated from protobuf message <code>opencensus.proto.agent.common.v1.Node</code>
 */
class Node extends \Google\Protobuf\Internal\Message
{
    /**
     * Identifier that uniquely identifies a process within a VM/container.
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.ProcessIdentifier identifier = 1;</code>
     */
    private $identifier = null;
    /**
     * Information on the OpenCensus Library that initiates the stream.
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.LibraryInfo library_info = 2;</code>
     */
    private $library_info = null;
    /**
     * Additional information on service.
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.ServiceInfo service_info = 3;</code>
     */
    private $service_info = null;
    /**
     * Additional attributes.
     *
     * Generated from protobuf field <code>map<string, string> attributes = 4;</code>
     */
    private $attributes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Opencensus\Proto\Agent\Common\V1\ProcessIdentifier $identifier
     *           Identifier that uniquely identifies a process within a VM/container.
     *     @type \Opencensus\Proto\Agent\Common\V1\LibraryInfo $library_info
     *           Information on the OpenCensus Library that initiates the stream.
     *     @type \Opencensus\Proto\Agent\Common\V1\ServiceInfo $service_info
     *           Additional information on service.
     *     @type array|\Google\Protobuf\Internal\MapField $attributes
     *           Additional attributes.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Agent\Common\V1\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Identifier that uniquely identifies a process within a VM/container.
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.ProcessIdentifier identifier = 1;</code>
     * @return \Opencensus\Proto\Agent\Common\V1\ProcessIdentifier
     */
    public function getIdentifier()
    {
        return $this->identifier;
    }

    /**
     * Identifier that uniquely identifies a process within a VM/container.
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.ProcessIdentifier identifier = 1;</code>
     * @param \Opencensus\Proto\Agent\Common\V1\ProcessIdentifier $var
     * @return $this
     */
    public function setIdentifier($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Agent\Common\V1\ProcessIdentifier::class);
        $this->identifier = $var;

        return $this;
    }

    /**
     * Information on the OpenCensus Library that initiates the stream.
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.LibraryInfo library_info = 2;</code>
     * @return \Opencensus\Proto\Agent\Common\V1\LibraryInfo
     */
    public function getLibraryInfo()
    {
        return $this->library_info;
    }

    /**
     * Information on the OpenCensus Library that initiates the stream.
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.LibraryInfo library_info = 2;</code>
     * @param \Opencensus\Proto\Agent\Common\V1\LibraryInfo $var
     * @return $this
     */
    public function setLibraryInfo($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Agent\Common\V1\LibraryInfo::class);
        $this->library_info = $var;

        return $this;
    }

    /**
     * Additional information on service.
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.ServiceInfo service_info = 3;</code>
     * @return \Opencensus\Proto\Agent\Common\V1\ServiceInfo
     */
    public function getServiceInfo()
    {
        return $this->service_info;
    }

    /**
     * Additional information on service.
     *
     * Generated from protobuf field <code>.opencensus.proto.agent.common.v1.ServiceInfo service_info = 3;</code>
     * @param \Opencensus\Proto\Agent\Common\V1\ServiceInfo $var
     * @return $this
     */
    public function setServiceInfo($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Agent\Common\V1\ServiceInfo::class);
        $this->service_info = $var;

        return $this;
    }

    /**
     * Additional attributes.
     *
     * Generated from protobuf field <code>map<string, string> attributes = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Additional attributes.
     *
     * Generated from protobuf field <code>map<string, string> attributes = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAttributes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->attributes = $arr;

        return $this;
    }

}

