<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/agent/common/v1/common.proto

namespace Opencensus\Proto\Agent\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Identifier that uniquely identifies a process within a VM/container.
 *
 * Generated from protobuf message <code>opencensus.proto.agent.common.v1.ProcessIdentifier</code>
 */
class ProcessIdentifier extends \Google\Protobuf\Internal\Message
{
    /**
     * The host name. Usually refers to the machine/container name.
     * For example: os.Hostname() in Go, socket.gethostname() in Python.
     *
     * Generated from protobuf field <code>string host_name = 1;</code>
     */
    private $host_name = '';
    /**
     * Process id.
     *
     * Generated from protobuf field <code>uint32 pid = 2;</code>
     */
    private $pid = 0;
    /**
     * Start time of this ProcessIdentifier. Represented in epoch time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_timestamp = 3;</code>
     */
    private $start_timestamp = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $host_name
     *           The host name. Usually refers to the machine/container name.
     *           For example: os.Hostname() in Go, socket.gethostname() in Python.
     *     @type int $pid
     *           Process id.
     *     @type \Google\Protobuf\Timestamp $start_timestamp
     *           Start time of this ProcessIdentifier. Represented in epoch time.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Agent\Common\V1\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * The host name. Usually refers to the machine/container name.
     * For example: os.Hostname() in Go, socket.gethostname() in Python.
     *
     * Generated from protobuf field <code>string host_name = 1;</code>
     * @return string
     */
    public function getHostName()
    {
        return $this->host_name;
    }

    /**
     * The host name. Usually refers to the machine/container name.
     * For example: os.Hostname() in Go, socket.gethostname() in Python.
     *
     * Generated from protobuf field <code>string host_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHostName($var)
    {
        GPBUtil::checkString($var, True);
        $this->host_name = $var;

        return $this;
    }

    /**
     * Process id.
     *
     * Generated from protobuf field <code>uint32 pid = 2;</code>
     * @return int
     */
    public function getPid()
    {
        return $this->pid;
    }

    /**
     * Process id.
     *
     * Generated from protobuf field <code>uint32 pid = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPid($var)
    {
        GPBUtil::checkUint32($var);
        $this->pid = $var;

        return $this;
    }

    /**
     * Start time of this ProcessIdentifier. Represented in epoch time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_timestamp = 3;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getStartTimestamp()
    {
        return $this->start_timestamp;
    }

    /**
     * Start time of this ProcessIdentifier. Represented in epoch time.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp start_timestamp = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setStartTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->start_timestamp = $var;

        return $this;
    }

}

