<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/resource/v1/resource.proto

namespace GPBMetadata\Opencensus\Proto\Resource\V1;

class Resource
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afc020a2b6f70656e63656e7375732f70726f746f2f7265736f75726365" .
            "2f76312f7265736f757263652e70726f746f121c6f70656e63656e737573" .
            "2e70726f746f2e7265736f757263652e7631228b010a085265736f757263" .
            "65120c0a047479706518012001280912420a066c6162656c731802200328" .
            "0b32322e6f70656e63656e7375732e70726f746f2e7265736f757263652e" .
            "76312e5265736f757263652e4c6162656c73456e7472791a2d0a0b4c6162" .
            "656c73456e747279120b0a036b6579180120012809120d0a0576616c7565" .
            "1802200128093a0238014298010a1f696f2e6f70656e63656e7375732e70" .
            "726f746f2e7265736f757263652e7631420d5265736f7572636550726f74" .
            "6f50015a456769746875622e636f6d2f63656e7375732d696e737472756d" .
            "656e746174696f6e2f6f70656e63656e7375732d70726f746f2f67656e2d" .
            "676f2f7265736f757263652f7631ea021c4f70656e43656e7375732e5072" .
            "6f746f2e5265736f757263652e5631620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

