<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/trace/v1/trace.proto

namespace Opencensus\Proto\Trace\V1\Span;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A set of attributes, each with a key and a value.
 *
 * Generated from protobuf message <code>opencensus.proto.trace.v1.Span.Attributes</code>
 */
class Attributes extends \Google\Protobuf\Internal\Message
{
    /**
     * The set of attributes. The value can be a string, an integer, a double
     * or the Boolean values `true` or `false`. Note, global attributes like 
     * server name can be set as tags using resource API. Examples of attributes:
     *     "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
     *     "/http/server_latency": 300
     *     "abc.com/myattribute": true
     *     "abc.com/score": 10.239
     *
     * Generated from protobuf field <code>map<string, .opencensus.proto.trace.v1.AttributeValue> attribute_map = 1;</code>
     */
    private $attribute_map;
    /**
     * The number of attributes that were discarded. Attributes can be discarded
     * because their keys are too long or because there are too many attributes.
     * If this value is 0, then no attributes were dropped.
     *
     * Generated from protobuf field <code>int32 dropped_attributes_count = 2;</code>
     */
    private $dropped_attributes_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $attribute_map
     *           The set of attributes. The value can be a string, an integer, a double
     *           or the Boolean values `true` or `false`. Note, global attributes like 
     *           server name can be set as tags using resource API. Examples of attributes:
     *               "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
     *               "/http/server_latency": 300
     *               "abc.com/myattribute": true
     *               "abc.com/score": 10.239
     *     @type int $dropped_attributes_count
     *           The number of attributes that were discarded. Attributes can be discarded
     *           because their keys are too long or because there are too many attributes.
     *           If this value is 0, then no attributes were dropped.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Trace\V1\Trace::initOnce();
        parent::__construct($data);
    }

    /**
     * The set of attributes. The value can be a string, an integer, a double
     * or the Boolean values `true` or `false`. Note, global attributes like 
     * server name can be set as tags using resource API. Examples of attributes:
     *     "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
     *     "/http/server_latency": 300
     *     "abc.com/myattribute": true
     *     "abc.com/score": 10.239
     *
     * Generated from protobuf field <code>map<string, .opencensus.proto.trace.v1.AttributeValue> attribute_map = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAttributeMap()
    {
        return $this->attribute_map;
    }

    /**
     * The set of attributes. The value can be a string, an integer, a double
     * or the Boolean values `true` or `false`. Note, global attributes like 
     * server name can be set as tags using resource API. Examples of attributes:
     *     "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
     *     "/http/server_latency": 300
     *     "abc.com/myattribute": true
     *     "abc.com/score": 10.239
     *
     * Generated from protobuf field <code>map<string, .opencensus.proto.trace.v1.AttributeValue> attribute_map = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAttributeMap($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opencensus\Proto\Trace\V1\AttributeValue::class);
        $this->attribute_map = $arr;

        return $this;
    }

    /**
     * The number of attributes that were discarded. Attributes can be discarded
     * because their keys are too long or because there are too many attributes.
     * If this value is 0, then no attributes were dropped.
     *
     * Generated from protobuf field <code>int32 dropped_attributes_count = 2;</code>
     * @return int
     */
    public function getDroppedAttributesCount()
    {
        return $this->dropped_attributes_count;
    }

    /**
     * The number of attributes that were discarded. Attributes can be discarded
     * because their keys are too long or because there are too many attributes.
     * If this value is 0, then no attributes were dropped.
     *
     * Generated from protobuf field <code>int32 dropped_attributes_count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDroppedAttributesCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->dropped_attributes_count = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Attributes::class, \Opencensus\Proto\Trace\V1\Span_Attributes::class);

