<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/trace/v1/trace.proto

namespace Opencensus\Proto\Trace\V1\Span;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * This field conveys information about request position in multiple distributed tracing graphs.
 * It is a list of Tracestate.Entry with a maximum of 32 members in the list.
 * See the https://github.com/w3c/distributed-tracing for more details about this field.
 *
 * Generated from protobuf message <code>opencensus.proto.trace.v1.Span.Tracestate</code>
 */
class Tracestate extends \Google\Protobuf\Internal\Message
{
    /**
     * A list of entries that represent the Tracestate.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.trace.v1.Span.Tracestate.Entry entries = 1;</code>
     */
    private $entries;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Opencensus\Proto\Trace\V1\Span\Tracestate\Entry[]|\Google\Protobuf\Internal\RepeatedField $entries
     *           A list of entries that represent the Tracestate.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Trace\V1\Trace::initOnce();
        parent::__construct($data);
    }

    /**
     * A list of entries that represent the Tracestate.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.trace.v1.Span.Tracestate.Entry entries = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEntries()
    {
        return $this->entries;
    }

    /**
     * A list of entries that represent the Tracestate.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.trace.v1.Span.Tracestate.Entry entries = 1;</code>
     * @param \Opencensus\Proto\Trace\V1\Span\Tracestate\Entry[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEntries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opencensus\Proto\Trace\V1\Span\Tracestate\Entry::class);
        $this->entries = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Tracestate::class, \Opencensus\Proto\Trace\V1\Span_Tracestate::class);

