<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/trace/v1/trace.proto

namespace Opencensus\Proto\Trace\V1\StackTrace;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A single stack frame in a stack trace.
 *
 * Generated from protobuf message <code>opencensus.proto.trace.v1.StackTrace.StackFrame</code>
 */
class StackFrame extends \Google\Protobuf\Internal\Message
{
    /**
     * The fully-qualified name that uniquely identifies the function or
     * method that is active in this frame.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TruncatableString function_name = 1;</code>
     */
    private $function_name = null;
    /**
     * An un-mangled function name, if `function_name` is
     * [mangled](http://www.avabodh.com/cxxin/namemangling.html). The name can
     * be fully qualified.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TruncatableString original_function_name = 2;</code>
     */
    private $original_function_name = null;
    /**
     * The name of the source file where the function call appears.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TruncatableString file_name = 3;</code>
     */
    private $file_name = null;
    /**
     * The line number in `file_name` where the function call appears.
     *
     * Generated from protobuf field <code>int64 line_number = 4;</code>
     */
    private $line_number = 0;
    /**
     * The column number where the function call appears, if available.
     * This is important in JavaScript because of its anonymous functions.
     *
     * Generated from protobuf field <code>int64 column_number = 5;</code>
     */
    private $column_number = 0;
    /**
     * The binary module from where the code was loaded.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.Module load_module = 6;</code>
     */
    private $load_module = null;
    /**
     * The version of the deployed source code.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TruncatableString source_version = 7;</code>
     */
    private $source_version = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Opencensus\Proto\Trace\V1\TruncatableString $function_name
     *           The fully-qualified name that uniquely identifies the function or
     *           method that is active in this frame.
     *     @type \Opencensus\Proto\Trace\V1\TruncatableString $original_function_name
     *           An un-mangled function name, if `function_name` is
     *           [mangled](http://www.avabodh.com/cxxin/namemangling.html). The name can
     *           be fully qualified.
     *     @type \Opencensus\Proto\Trace\V1\TruncatableString $file_name
     *           The name of the source file where the function call appears.
     *     @type int|string $line_number
     *           The line number in `file_name` where the function call appears.
     *     @type int|string $column_number
     *           The column number where the function call appears, if available.
     *           This is important in JavaScript because of its anonymous functions.
     *     @type \Opencensus\Proto\Trace\V1\Module $load_module
     *           The binary module from where the code was loaded.
     *     @type \Opencensus\Proto\Trace\V1\TruncatableString $source_version
     *           The version of the deployed source code.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Trace\V1\Trace::initOnce();
        parent::__construct($data);
    }

    /**
     * The fully-qualified name that uniquely identifies the function or
     * method that is active in this frame.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TruncatableString function_name = 1;</code>
     * @return \Opencensus\Proto\Trace\V1\TruncatableString
     */
    public function getFunctionName()
    {
        return $this->function_name;
    }

    /**
     * The fully-qualified name that uniquely identifies the function or
     * method that is active in this frame.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TruncatableString function_name = 1;</code>
     * @param \Opencensus\Proto\Trace\V1\TruncatableString $var
     * @return $this
     */
    public function setFunctionName($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Trace\V1\TruncatableString::class);
        $this->function_name = $var;

        return $this;
    }

    /**
     * An un-mangled function name, if `function_name` is
     * [mangled](http://www.avabodh.com/cxxin/namemangling.html). The name can
     * be fully qualified.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TruncatableString original_function_name = 2;</code>
     * @return \Opencensus\Proto\Trace\V1\TruncatableString
     */
    public function getOriginalFunctionName()
    {
        return $this->original_function_name;
    }

    /**
     * An un-mangled function name, if `function_name` is
     * [mangled](http://www.avabodh.com/cxxin/namemangling.html). The name can
     * be fully qualified.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TruncatableString original_function_name = 2;</code>
     * @param \Opencensus\Proto\Trace\V1\TruncatableString $var
     * @return $this
     */
    public function setOriginalFunctionName($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Trace\V1\TruncatableString::class);
        $this->original_function_name = $var;

        return $this;
    }

    /**
     * The name of the source file where the function call appears.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TruncatableString file_name = 3;</code>
     * @return \Opencensus\Proto\Trace\V1\TruncatableString
     */
    public function getFileName()
    {
        return $this->file_name;
    }

    /**
     * The name of the source file where the function call appears.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TruncatableString file_name = 3;</code>
     * @param \Opencensus\Proto\Trace\V1\TruncatableString $var
     * @return $this
     */
    public function setFileName($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Trace\V1\TruncatableString::class);
        $this->file_name = $var;

        return $this;
    }

    /**
     * The line number in `file_name` where the function call appears.
     *
     * Generated from protobuf field <code>int64 line_number = 4;</code>
     * @return int|string
     */
    public function getLineNumber()
    {
        return $this->line_number;
    }

    /**
     * The line number in `file_name` where the function call appears.
     *
     * Generated from protobuf field <code>int64 line_number = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLineNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->line_number = $var;

        return $this;
    }

    /**
     * The column number where the function call appears, if available.
     * This is important in JavaScript because of its anonymous functions.
     *
     * Generated from protobuf field <code>int64 column_number = 5;</code>
     * @return int|string
     */
    public function getColumnNumber()
    {
        return $this->column_number;
    }

    /**
     * The column number where the function call appears, if available.
     * This is important in JavaScript because of its anonymous functions.
     *
     * Generated from protobuf field <code>int64 column_number = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setColumnNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->column_number = $var;

        return $this;
    }

    /**
     * The binary module from where the code was loaded.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.Module load_module = 6;</code>
     * @return \Opencensus\Proto\Trace\V1\Module
     */
    public function getLoadModule()
    {
        return $this->load_module;
    }

    /**
     * The binary module from where the code was loaded.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.Module load_module = 6;</code>
     * @param \Opencensus\Proto\Trace\V1\Module $var
     * @return $this
     */
    public function setLoadModule($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Trace\V1\Module::class);
        $this->load_module = $var;

        return $this;
    }

    /**
     * The version of the deployed source code.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TruncatableString source_version = 7;</code>
     * @return \Opencensus\Proto\Trace\V1\TruncatableString
     */
    public function getSourceVersion()
    {
        return $this->source_version;
    }

    /**
     * The version of the deployed source code.
     *
     * Generated from protobuf field <code>.opencensus.proto.trace.v1.TruncatableString source_version = 7;</code>
     * @param \Opencensus\Proto\Trace\V1\TruncatableString $var
     * @return $this
     */
    public function setSourceVersion($var)
    {
        GPBUtil::checkMessage($var, \Opencensus\Proto\Trace\V1\TruncatableString::class);
        $this->source_version = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(StackFrame::class, \Opencensus\Proto\Trace\V1\StackTrace_StackFrame::class);

