<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/trace/v1/trace.proto

namespace Opencensus\Proto\Trace\V1\StackTrace;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A collection of stack frames, which can be truncated.
 *
 * Generated from protobuf message <code>opencensus.proto.trace.v1.StackTrace.StackFrames</code>
 */
class StackFrames extends \Google\Protobuf\Internal\Message
{
    /**
     * Stack frames in this call stack.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.trace.v1.StackTrace.StackFrame frame = 1;</code>
     */
    private $frame;
    /**
     * The number of stack frames that were dropped because there
     * were too many stack frames.
     * If this value is 0, then no stack frames were dropped.
     *
     * Generated from protobuf field <code>int32 dropped_frames_count = 2;</code>
     */
    private $dropped_frames_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Opencensus\Proto\Trace\V1\StackTrace\StackFrame[]|\Google\Protobuf\Internal\RepeatedField $frame
     *           Stack frames in this call stack.
     *     @type int $dropped_frames_count
     *           The number of stack frames that were dropped because there
     *           were too many stack frames.
     *           If this value is 0, then no stack frames were dropped.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Trace\V1\Trace::initOnce();
        parent::__construct($data);
    }

    /**
     * Stack frames in this call stack.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.trace.v1.StackTrace.StackFrame frame = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFrame()
    {
        return $this->frame;
    }

    /**
     * Stack frames in this call stack.
     *
     * Generated from protobuf field <code>repeated .opencensus.proto.trace.v1.StackTrace.StackFrame frame = 1;</code>
     * @param \Opencensus\Proto\Trace\V1\StackTrace\StackFrame[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFrame($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Opencensus\Proto\Trace\V1\StackTrace\StackFrame::class);
        $this->frame = $arr;

        return $this;
    }

    /**
     * The number of stack frames that were dropped because there
     * were too many stack frames.
     * If this value is 0, then no stack frames were dropped.
     *
     * Generated from protobuf field <code>int32 dropped_frames_count = 2;</code>
     * @return int
     */
    public function getDroppedFramesCount()
    {
        return $this->dropped_frames_count;
    }

    /**
     * The number of stack frames that were dropped because there
     * were too many stack frames.
     * If this value is 0, then no stack frames were dropped.
     *
     * Generated from protobuf field <code>int32 dropped_frames_count = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDroppedFramesCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->dropped_frames_count = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(StackFrames::class, \Opencensus\Proto\Trace\V1\StackTrace_StackFrames::class);

