<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opencensus/proto/trace/v1/trace.proto

namespace Opencensus\Proto\Trace\V1\Span\Tracestate;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>opencensus.proto.trace.v1.Span.Tracestate.Entry</code>
 */
class Entry extends \Google\Protobuf\Internal\Message
{
    /**
     * The key must begin with a lowercase letter, and can only contain
     * lowercase letters 'a'-'z', digits '0'-'9', underscores '_', dashes
     * '-', asterisks '*', and forward slashes '/'.
     *
     * Generated from protobuf field <code>string key = 1;</code>
     */
    private $key = '';
    /**
     * The value is opaque string up to 256 characters printable ASCII
     * RFC0020 characters (i.e., the range 0x20 to 0x7E) except ',' and '='.
     * Note that this also excludes tabs, newlines, carriage returns, etc.
     *
     * Generated from protobuf field <code>string value = 2;</code>
     */
    private $value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *           The key must begin with a lowercase letter, and can only contain
     *           lowercase letters 'a'-'z', digits '0'-'9', underscores '_', dashes
     *           '-', asterisks '*', and forward slashes '/'.
     *     @type string $value
     *           The value is opaque string up to 256 characters printable ASCII
     *           RFC0020 characters (i.e., the range 0x20 to 0x7E) except ',' and '='.
     *           Note that this also excludes tabs, newlines, carriage returns, etc.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Opencensus\Proto\Trace\V1\Trace::initOnce();
        parent::__construct($data);
    }

    /**
     * The key must begin with a lowercase letter, and can only contain
     * lowercase letters 'a'-'z', digits '0'-'9', underscores '_', dashes
     * '-', asterisks '*', and forward slashes '/'.
     *
     * Generated from protobuf field <code>string key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * The key must begin with a lowercase letter, and can only contain
     * lowercase letters 'a'-'z', digits '0'-'9', underscores '_', dashes
     * '-', asterisks '*', and forward slashes '/'.
     *
     * Generated from protobuf field <code>string key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * The value is opaque string up to 256 characters printable ASCII
     * RFC0020 characters (i.e., the range 0x20 to 0x7E) except ',' and '='.
     * Note that this also excludes tabs, newlines, carriage returns, etc.
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * The value is opaque string up to 256 characters printable ASCII
     * RFC0020 characters (i.e., the range 0x20 to 0x7E) except ',' and '='.
     * Note that this also excludes tabs, newlines, carriage returns, etc.
     *
     * Generated from protobuf field <code>string value = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Entry::class, \Opencensus\Proto\Trace\V1\Span_Tracestate_Entry::class);

